name: Weekly URL Processing

on:
  schedule:
    - cron: '0 0 * * 1'  # 每天UTC 0点执行，即周一 8:00 (北京时间，如果需要调整时区，请自行修改cron表达式)
  workflow_dispatch: # 允许手动触发

jobs:
  process-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # 选择一个合适的 Python 版本

    - name: Install dependencies
      run: pip install requests

    - name: Define URL Groups and Output Files (YAML List)
      id: define-inputs
      run: |
        echo "::set-output name=url_groups::[
          {\"urls\": [\"https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Pinduoduo/Pinduoduo.list\", \"https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/BiliBili/BiliBili.list\"], \"output\": \"a.list\"},
          {\"urls\": [\"https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Baidu/Baidu.list\", \"https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Weibo/Weibo.list\"], \"output\": \"b.list\"}
        ]"

    - name: Run Python script
      run: python process.py
      env:
        URL_GROUPS: ${{ steps.define-inputs.outputs.url_groups }}
